### ISSUE TITLE
Reduce the verbosity of the slack reporter 

### ISSUE THREAD

**Issue by aamorozov** [ngs/nightwatch-slack-reporter#6]
Hi @ngs ! First-off, great job on the integration! 

How can you reduce the verbose logs from test suit? Currently, it logs the result from each test case that runs within a test suit, which sometime may contain 10-20-30 or more test cases. How to make logs in Slack to show the total number of passed/failed test cases but without verbose output for each test case?

**Comment by Dobbychen** [comment]
Actually the latest pull request (https://github.com/ngs/nightwatch-slack-reporter/pull/3) has solved the problem. Your can set `slack_send_only_failed_tests : true`  to achieve this. 

However, this feature is not updated in the npm repo yet. (As `npm nightwatch-slack-reporter` stills downloads commit from Sep, 2016)

**Comment by aamorozov** [comment]
Resolved it
